version: '3.8'
services:
  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=ROOTNAME
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9090"
